version: "3.9"

services:
  web:
    build: 
      context: .
      target: dev
    command: air
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: "on-failure"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "54321:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: "on-failure"

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: "on-failure"

volumes:
  postgres-db: